title: 'nimesh chahare'
description: "personal webpage"
baseurl: "/lite"
url: "https://nchahare.github.io"

header_pages:
  - index.md
  - cv.md
  - about.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://twitter.com/onenimesa">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
